# Generated by Django 6.0 on 2026-04-28 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('brand', models.CharField(default='un-branded', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, help_text='Date when product was first added')),
                ('quantity_available', models.IntegerField(default=0, help_text='Current stock available')),
                ('quantity_sold', models.IntegerField(default=0, help_text='Total quantity sold')),
                ('total_price_sold', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue from this product', max_digits=10)),
                ('last_sold_date', models.DateTimeField(blank=True, help_text='Last date this product was sold', null=True)),
                ('payment_successful', models.BooleanField(default=False, help_text='Has this product been successfully sold at least once')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='The topic this category belongs to (e.g. Video Games)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='store.topic'),
        ),
    ]
