# Generated by Django 6.0 on 2026-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upc_code',
            field=models.CharField(blank=True, db_index=True, help_text='Universal Product Code (UPC/EAN barcode number)', max_length=20, null=True, unique=True),
        ),
    ]
