# Generated by Django 6.0 on 2026-05-04 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, help_text='PayPal capture/transaction ID — required for programmatic refunds', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='condition_acceptable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='quantity_to_refund',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='refunditem',
            name='restocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='admin_verified',
            field=models.BooleanField(default=False, help_text="Must be set before PayPal refund or completion actions can run. Use 'Verify & approve refund requests' action."),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='paypal_refund_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to refund via PayPal (what customer actually paid in cash)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='rewards_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rewards used in original purchase', max_digits=10),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_refunds', to=settings.AUTH_USER_MODEL),
        ),
    ]
